### ISSUE TITLE
isFluidWidth prop

### ISSUE THREAD

**Issue by vojthor** [gooftroop/react-image-magnify#1]
Hey, first of all, great work on that fork!

Is there any way of mimicking **isFluidWidth** prop as it seems it was removed?

Thanks!

**Comment by gooftroop** [comment]
Hi @vojthor! The content is fluid width by default, unless you provide static sizing. Are you seeing a contrary behavior?

**Comment by gooftroop** [comment]
Hi @vojthor I will assume that you've resolved your question and will close this issue
