### ISSUE TITLE
server side rendering not supported

### ISSUE THREAD

**Issue by bhavikagrawal** [gooftroop/react-image-magnify#4]

**Comment by gooftroop** [comment]
Hi @bhavikagrawal can you provide either a sandbox reproducing the error or more information on your ecosystem and any errors you are seeing?

**Comment by bhavikagrawal** [comment]
Please check code sandbox: https://codesandbox.io/s/ssr-react-image-magnify-fs7xh.

I do not see an

**Comment by bhavikagrawal** [comment]
The issue is no longer relevent. It is working fine on SSR

**Comment by bhavikagrawal** [comment]
I am able to reproduce the issue. It seems, that the issue is only with scene7 images. 

I was able to reproduce the issue 9/10 times. 

https://user-images.githubusercontent.com/8545242/152532113-d125984c-e924-4a0b-8dd3-1b03c85f2570.mov


[code-sandbox](https://codesandbox.io/s/ssr-react-image-magnify-fs7xh?file=/src/components/Layout.js)

**Comment by bhavikagrawal** [comment]
@gooftroop 
The library is using the _onLoad_ event to apply zoom functionality.  Whereas _onLoad_ is only called if the resource/image is not loaded. 
But if it has already been loaded once, then it will be served from cache, the next time. _onLoad_ is never called again for subsequent SSRs until the cache is disabled or image source is changed. [Reference 1](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onload) [Reference 2](https://developer.samsung.com/smarttv/develop/legacy-platform-library/tec00151/index.html)

The reason it is working for https://picsum.photos/id/1018/200 is that it gets a 302 with another URL to render and thus calls onLoad, as image Source changes.

**Comment by RishikeshDarandale** [comment]
@gooftroop , Can you please help us in this one?

**Comment by bhavikagrawal** [comment]
@gooftroop any update on this?

**Comment by gooftroop** [comment]
Hi @bhavikagrawal I apologize for the delay - work has me pretty busy. As a quick note, this library does use hooks, so class-based components are not recommended. That being said, can you provide some more information about the browser environment(s) you are using? The bug you linked is specifically for samsung browsers. Can you also state what the bug is or what the desired behavior is?

**Comment by bhavikagrawal** [comment]
@gooftroop No problem, I understand.
The class-based component is just for reference, I have now changed it to a functional one.

I tested the feature on(NOT WORKING):
Mac OS Monterey 12.2.1 - Chrome(Version 98.0.4758.102 (Official Build) (x86_64))
Mac OS Monterey 12.2.1 - Microsoft Edge(Version 98.0.1108.56 (Official build) (x86_64))

It works fine on:
Mac OS Monterey 12.2.1 - Firefox(97.0.1 (64-bit)) , Safari(Version 15.3 (17612.4.9.1.8))

Issue: When you directly hit https://fs7xh.sse.codesandbox.io/, you can check, you will not be able to see image _onload_ event not called, because of which you will not see _Click to zoom_ icon and functionality missing.

Let me know if you need more information.

**Comment by gooftroop** [comment]
Hi @bhavikagrawal after some investigation, this is not due to a missing onload event, but rather something else. I'm going to continue to look into this. As a quick test, what happens when you change the interaction type from "hover" to "click"?

**Comment by bhavikagrawal** [comment]
@gooftroop Thanks for looking into it.

The experience remains the same for both "hover" and "click". No zoom functionality gets triggered.

**Comment by gooftroop** [comment]
@bhavikagrawal thank you trying that out. That's interesting - I was seeing a different behavior. What browser and OS were you on when you tested that?

**Comment by bhavikagrawal** [comment]
@gooftroop I have tested on
Mac OS Monterey 12.3 - Chrome(Version 99.0.4844.74 (Official Build) (x86_64))

I was able to reproduce the scenario 7/10 times with "click"

Please also refer to the [comment](https://github.com/gooftroop/react-image-magnify/issues/4#issuecomment-1031403414) for possible cause if that helps.

**Comment by gooftroop** [comment]
@bhavikagrawal I just pushed v4.1.0 and verified that your sandbox now works as expected
